language: ruby
cache: bundler
sudo: false
rvm:
- 2.0.0
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
script:
- bundle exec rake db:schema:load
- bundle exec rake
addons:
  code_climate:
    repo_token: 820e155f1bff3d5cfcb84eae1caace7cd9ec5a27540f52222620896dc010b3ee
env:
  matrix:
  - CODECLIMATE_REPO_TOKEN=820e155f1bff3d5cfcb84eae1caace7cd9ec5a27540f52222620896dc010b3ee
  global:
    secure: D6DUhdYaXDL0/LdpTB2ESBpwLbrnRFc13i/Uuh8wnvSbzqIqHPgfOtiY4+kLHskOeeJuur7Tka/ApYG9HqJWFG89SJToLH6K/pRBbJCXqWWPgbaR2KAgOs106h7CE83HS4/NkuTp884uaQCBILueHvt/Ld5TuVyNdP2DUyEdDaA=
before_install:
- openssl aes-256-cbc -K $encrypted_81250995bc45_key -iv $encrypted_81250995bc45_iv
  -in escualo_rsa.enc -out escualo_rsa -d
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo-deploy/master/travis_deploy && chmod u+x travis_deploy
- ./travis_deploy atheneum
