language: ruby
cache: bundler
sudo: false
rvm:
- 2.0.0
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
script:
- bundle exec rake db:schema:load
- bundle exec rake
after_success:
- test ! -z "$TRAVIS_TAG" && git checkout master && git reset --hard $TRAVIS_TAG
deploy:
  provider: openshift
  user: flbulgarelli@yahoo.com.ar
  password:
    secure: jgsXU+UQUUK2p1ixFW2eAb2Trcwm4rYGFADQoPvllPZa9bR18Kt4DLfLOeZIZBXTHv8MK+4IdAQVFH7M48k5cDuf+JYaYM2paDnk4Q+r+R2uudu0CdzcAFTYLdKrZSqZhp7f5Llu3HAlo1uqYviMsX8nQ0zyRMGnaDsIZFL/Z8Q=
  app: platform
  domain: mumuki
  on:
    tags: true
    repo: mumuki/mumuki-atheneum

addons:
  code_climate:
    repo_token: 820e155f1bff3d5cfcb84eae1caace7cd9ec5a27540f52222620896dc010b3ee
env: CODECLIMATE_REPO_TOKEN=820e155f1bff3d5cfcb84eae1caace7cd9ec5a27540f52222620896dc010b3ee
