language: ruby
cache: bundler
sudo: false
git:
  depth: 500
rvm:
- 2.0.0
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
script:
- bundle exec rake db:schema:load
- bundle exec rake
after_success:
- wget https://raw.githubusercontent.com/mumuki/mumuki-escualo/master/travis_deploy && 
  chmod u+x travis_deploy &&
  ./travis_deploy atheneum atheneum1.mumuki.io &&
  ./travis_deploy atheneum atheneum2.mumuki.io
addons:
  code_climate:
    repo_token: 820e155f1bff3d5cfcb84eae1caace7cd9ec5a27540f52222620896dc010b3ee
env: CODECLIMATE_REPO_TOKEN=820e155f1bff3d5cfcb84eae1caace7cd9ec5a27540f52222620896dc010b3ee
before_install:
- openssl aes-256-cbc -K $encrypted_81250995bc45_key -iv $encrypted_81250995bc45_iv
  -in escualo_rsa.enc -out escualo_rsa -d
