language: ruby
rvm:
 - 2.0.0
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq ghc cabal-debian
 - cabal install hspec
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
